apiVersion: v1
kind: Service
metadata:
  name: voting-app-servoce
  labels:
    name: voting-app-service
    app: demo-voting-app
spec:
  selector:
    name: voting-app-pod
    app: demo-voting-app
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30004
